# Generated by Django 5.2.6 on 2025-10-12 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='active',
        ),
        migrations.RemoveField(
            model_name='book',
            name='photo_author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='rental_period',
        ),
    ]
