# Generated by Django 5.2.6 on 2025-10-12 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0005_alter_book_photo_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='photo_book',
            field=models.ImageField(blank=True, null=True, upload_to='bocks'),
        ),
    ]
