# Generated by Django 5.2.7 on 2025-10-15 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0009_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='text',
        ),
    ]
